blank_issues_enabled: false
contact_links:
  - name: Installation, configuration issue
    url: https://forum.cryptpad.org
    about: Please use the appropriate forum category for questions or assistance
  - name: Bug report
    url: https://forum.cryptpad.org
    about: Please use the appropriate forum category to report bugs
  - name: Feature request
    url: https://forum.cryptpad.org
    about: Please use the appropriate forum category for features requests