name: Feature Request
description: Suggest an idea for CryptPad.
labels: ["Feature Request"]
body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the code of conduct before proceeding.
      options:
        - label: I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    attributes:
      label: I would like to request a new feature for CryptPad
      description: Prior to creating a new issue, please check following:** *(fill out each checkbox with an `X` once done)*
      options:
      - label: I have searched past issues and labels to check that my question/idea does not exist
        required: true
      - label: I have understood that this report is dedicated for feature requests, and not for support-related inquiries.
        required: true
      - label: I have understood that answers are voluntary and community-driven, and not commercial support.
        required: true
  - type: textarea
    attributes:
      label: Summary
      description: Please describe your idea in a reasonable amount of detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Please describe how your idea would benefit you and other users.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request.
